<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerK4ajluj\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerK4ajluj/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerK4ajluj.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerK4ajluj\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerK4ajluj\appProdProjectContainer([
    'container.build_hash' => 'K4ajluj',
    'container.build_id' => '9490a439',
    'container.build_time' => 1589818119,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerK4ajluj');
