<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBcsojoo\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBcsojoo/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerBcsojoo.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerBcsojoo\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerBcsojoo\appDevDebugProjectContainer([
    'container.build_hash' => 'Bcsojoo',
    'container.build_id' => '1f92456f',
    'container.build_time' => 1589817370,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBcsojoo');
